version: 2
registries:
  azure-devops:
    type: python-index
    url: ${{secrets.AZURE_DEVOPS_URL}}
    token: ${{secrets.AZURE_DEVOPS_PAT}}
    replaces-base: true
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    registries:
      - azure-devops
    assignees:
      - backwardspy
      - Mick-Cadac
