version: 2
registries:
  azure-devops:
    type: python-index
    url: "https://pkgs.dev.azure.com/binkhq/_packaging/binkhq/pypi/simple/"
    token: PAT:${{secrets.AZURE_DEVOPS_PAT}}
    replaces-base: true
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    insecure-external-code-execution: allow
    registries:
      - azure-devops
    assignees:
      - backwardspy
      - Mick-Cadac
