tests:
  script:
  - pip3 install --no-index --find-links=/wheelhouse -r requirements.txt
  - py.test app/tests/unit --cov=app --cov-config=.coveragerc-noagent

flake8:
  script:
    - flake8 *

deploy:
  stage: deploy
  script:
  - curl http://deployer.loyaltyangels.local/deploy/dev/midas
  only:
  - master