tests:
  script:
  - pip3 install -r requirements.txt
  - py.test app/tests/unit --cov=app --cov-config=.coveragerc-noagent

flake8:
  script:
    - flake8 *

deploy:
  image: boloyaltyangels/ansible
  stage: deploy
  script:
  - cd /ansible && ansible-playbook playbooks/deploy/flask.yml -e project=midas -e hosts=dev_web
  only:
  - master