"""add process steps

Revision ID: 3606b0fd222e
Revises:
Create Date: 2022-07-20 15:54:32.898494+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3606b0fd222e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "retry_task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("time_created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("request_data", sa.JSON(), nullable=False),
        sa.Column("journey_type", sa.String(), nullable=False),
        sa.Column("message_uid", sa.String(), nullable=False),
        sa.Column("scheme_account_id", sa.Integer(), nullable=False),
        sa.Column("scheme_identifier", sa.String(), nullable=False),
        sa.Column("next_attempt_time", sa.DateTime(), nullable=True),
        sa.Column(
            "status", sa.Enum("PENDING", "RETRYING", "FAILED", "SUCCESS", name="retrytaskstatuses"), nullable=False
        ),
        sa.Column("callback_retries", sa.Integer(), nullable=False),
        sa.Column("awaiting_callback", sa.Boolean(), nullable=False),
        sa.Column("process_steps", sa.ARRAY(sa.String()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message_uid"),
        sa.UniqueConstraint("scheme_account_id"),
    )
    op.create_index(op.f("ix_retry_task_status"), "retry_task", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_retry_task_status"), table_name="retry_task")
    op.drop_table("retry_task")
    # ### end Alembic commands ###
