# We possibly don't need the class path but we'll see

# These could be strings, if we end up with too many imports
# Commented entries are agents whose tests are currently not passing.
AGENTS = {
    # ----------- sandbox testing start -------------- #
    'iceland-bonus-card': 'iceland_merchant_integration.Iceland',
    'iceland-bonus-card-mock': 'mock_agents.MockAgentIce',
    'harvey-nichols-mock': 'mock_agents.MockAgentHN',
    'harvey-nichols': 'harvey_nichols.HarveyNichols',
    'performance-mock': 'performance_mock.MockPerformance',
    'performance-voucher-mock': 'performance_mock.MockPerformanceVoucher',
    # ----------- sandbox testing end ---------------- #
    'vibe-club': 'vibe_club.VibeClub',
    'maximiles': 'maximiles.Maximiles',
    'match-more': 'morrisons.Morrisons',
    'nectar': 'nectar.Nectar',
    'quidco': 'quidco.Quidco',
    'health-beautycard': 'superdrug.Superdrug',
    'tasty-rewards': 'tabletable.Tabletable',
    'tesco-clubcard': 'tesco.Tesco',
    'tesco-clubcard1': 'tesco.Tesco',
    'the-waterstones-card': 'waterstones.Waterstones',
    'frequent-flyer': 'qantas.Qantas',
    'the-perfume-shop': 'the_perfume_shop.ThePerfumeShop',
    'space-nk': 'space_nk.SpaceNK',
    'm-co-loyalty-card': 'mandco.MandCo',
    'sparks': 'sparks.Sparks',
    'virgin-flyingclub': 'virgin.Virgin',
    'rspb': 'rspb.RSPB',
    'together-rewards-card': 'the_works.TheWorks',
    'enrich': 'malaysia_airlines.MalaysiaAirlines',
    'royal-orchid-plus': 'thai_airways.ThaiAirways',
    'treat-me': 'paperchase.Paperchase',
    'priority-guest-rewards': 'priority_guest_rewards.PriorityGuestRewards',
    'omni': 'omni.Omni',
    'love-your-body': 'the_body_shop.TheBodyShop',
    'victoria': 'victoria.Victoria',
    'star-rewards': 'star_rewards.StarRewards',
    'the-garden-club': 'the_garden_club.TheGardenClub',
    'tkmaxx': 'tk_maxx.TKMaxx',
    'macdonald-hotels': 'the_club.TheClub',
    'marriott-rewards-card': 'marriott.Marriott',
    'showcase': 'showcase.Showcase',
    'stansted-farm': 'my360.My360',
    'the-courtyard': 'my360.My360',
    '19-fourteas-tea-rooms': 'my360.My360',
    'bored-of-southsea': 'my360.My360',
    'game-over': 'my360.My360',
    'watkins-and-faux': 'my360.My360',
    'northney-farm': 'my360.My360',
    'shakeadelic': 'my360.My360',
    'drift-bar': 'my360.My360',
    'poppins-restaurant': 'my360.My360',
    'polka-dot-piercing': 'my360.My360',
    'nanoo-hair': 'my360.My360',
    'comics-games-and-coffee': 'my360.My360',
    'the-richmond': 'my360.My360',
    'cliff-roe-sports': 'my360.My360',
    'michael-chell': 'my360.My360',
    'the-food-cellar': 'my360.My360',
    'hewetts': 'my360.My360',
    'fit-stuff': 'my360.My360',
    'cafe-copia': 'my360.My360',
    'bear-garden': 'my360.My360',
    'fresco-delikafessen': 'my360.My360',
    'henley-sports': 'my360.My360',
    'the-chocolate-cafe': 'my360.My360',
    'ted-james-barbershop': 'my360.My360',
    'bubble-city': 'my360.My360',
    'turners-pies': 'my360.My360',
    'gatsby-menswear': 'my360.My360',
    'linda-h': 'my360.My360',
    'tiffin-tea-rooms': 'my360.My360',
    'hilites-hair-and-beauty': 'my360.My360',
    'dhaba-lane': 'my360.My360',
    'deep-blue-restaurants': 'my360.My360',
    'el-mexicana': 'my360.My360',
    "fatface": "ecrebo.FatFace",
    "burger-king-rewards": "ecrebo.BurgerKing",
    "whsmith-rewards": "ecrebo.WhSmith",
    'whsmith-rewards-mock': 'mock_agents.MockAgentWHS',
    "wasabi-club": "acteol.Wasabi",
    "bpl-trenette": "bpl.Trenette",
}
