# List of my360 slugs and their respective api endpoint IDs
# Linked to Hermes my360endpoints.py

SCHEME_API_DICTIONARY = {
    'stansted-farm': 'cOqQmR',
    'the-courtyard': 'KbeClr',
    '19-fourteas-tea-rooms': 'Be_11k',
    'bored-of-southsea': 'UMxcnJ',
    'game-over': 'jpKJgU',
    'watkins-and-faux': 'HBWF65',
    'northney-farm': 'j5yAeE',
    'shakeadelic': 'NuNLGE',
    'drift-bar': 'iup7wK',
    'poppins-restaurant': 'C3HSb3',
    'polka-dot-piercing': '9jRSrq',
    'nanoo-hair': 'YSNMxs',
    'comics-games-and-coffee': 'GK4Tvh',
    'the-richmond': 'cM_Nh7',
    'tennessee-chicken': '',
    'cliff-roe-sports': 'K7yej1',
    'michael-chell': 'mchell',
    'the-food-cellar': '-fdK4i',
    'hewetts': 'hewtts',
    'fit-stuff': 'fitstu',
    'cafe-copia': 'rz22p1',
    'bear-garden': 'bearga',
    'fresco-delikafessen': '5rRCqF',
    'henley-sports': 'hsport',
    'the-chocolate-cafe': 'c1k2ks',
    'ted-james-barbershop': 'pQ1Pq1',
    'bubble-city': 'iIEWRM',
    'turners-pies': 'knT_d_',
    'gatsby-menswear': 'XgnCp2',
    'linda-h': 'lindah',
    'tiffin-tea-rooms': 'tiffin',
    'hilites-hair-and-beauty': 'bDqM2P',
    'dhaba-lane': 'P1irNK',
    'el-mexicana': 'KP6_Ox',
    'deep-blue-restaurants': '6qF7x1',
    # List of schemes to be added but no API code yet
    # 'mad-hatters': '',
    # 'peewees': '',
    # 'the-vestry': '',
    # 'laurence-menswear': '',
    # 'celo-tan-and-lash': '',
    # 'moffats': '',
    # 'strawberry-vibes': '',
    # 'magoos': '',
    # 'ians-barbers': '',
    # 'everybody-pilates': '',
    # 'nevaeh-hair': '',
    # 'the-marmion': '',
    # 'funland': '',
    # 'the-nags-head': '',
    # 'beauty-clinic': '',
    # 'grit-gym-mma-and-fitness': '',
    # 'the-coffee-co': '',
    # 'thousand-hills': '',
    # 'urban-food': '',
}
