from http import HTTPStatus, HTTPMethod

from app.tests.component.mocks import Endpoint

BASE_URL = "https://atreemouat.xxxitsucomms.co.uk"
ENDPOINTS = [
    Endpoint(
        HTTPMethod.POST,
        f"{BASE_URL}/api/Customer/FindCustomerDetails",
        HTTPStatus.OK,
        {
            "ResponseData": [
                {
                    "CtcID": 35,
                    "CpyID": 35,
                    "CreateDate": "2023-06-08T09:11:41",
                    "ModifiedDate": "2023-06-08T09:11:41",
                    "ModifiedBy": None,
                    "ModifiedByName": None,
                    "Source": "Bink",
                    "LastModifiedSource": None,
                    "MD5": "21f759d4187a42c2bf789e17df9784ba",
                    "ExternalIdentifier": {"ExternalID": "", "ExternalSource": "Bink"},
                    "PersonalDetails": {
                        "Title": None,
                        "FirstName": "Michael",
                        "LastName": "Morar",
                        "Email": "bink_mm@bink.com",
                        "MobilePhone": "",
                        "Phone": "",
                        "BirthDate": None,
                        "JobTitle": None,
                        "ParentEmailAddress": "",
                        "Gender": 0,
                        "CustomerAddress": {
                            "Address1": None,
                            "Address2": None,
                            "Address3": None,
                            "City": None,
                            "PostCode": None,
                            "StateName": None,
                            "CountryCode": None,
                            "Phone": None,
                        },
                        "DoNotExport": None,
                    },
                    "ReferrerDetails": None,
                    "LoyaltyDetails": {
                        "LoyaltyPointsBalance": 3.1,
                        "LoyaltyCashBalance": 0.0,
                        "LifeTimePoints": 0.0,
                        "CyclePointsBalance": 0.0,
                        "PointsNeededForNextRewards": 0.0,
                        "CurrentTiersName": "",
                        "TierLastUpdatedDate": None,
                        "NextTiersName": "",
                        "TiersExpirationDate": None,
                        "MemberNumbers": ["3287211356"],
                        "CardsToken": None,
                    },
                    "SupInfo": [
                        {"FieldName": "CompletedFavoriteMission", "FieldContent": ""},
                        {"FieldName": "CompletedLocationPermissionMission", "FieldContent": ""},
                        {"FieldName": "CompletedSocialShareMission", "FieldContent": ""},
                        {
                            "FieldName": "HashPassword",
                            "FieldContent": "$argon2id$v=19$m=16,t=2,p=1$MTIzNDU2Nzg$Dhk8fwnes+f9vzOwgdALlA",
                        },
                        {"FieldName": "pll_bink", "FieldContent": "false"},
                        {"FieldName": "pll_mixr", "FieldContent": ""},
                        {"FieldName": "ReferredByCode", "FieldContent": ""},
                        {"FieldName": "sample string 1", "FieldContent": "sample string 4"},
                        {"FieldName": "sample string 2", "FieldContent": ""},
                    ],
                    "MarketingOptin": None,
                    "Preferences": None,
                    "Interests": None,
                    "Tags": None,
                    "InteractionsInfo": None,
                    "ProcessMydata": True,
                    "IsSuspended": False,
                    "DeleteMyData": False,
                    "DoNotExport": False,
                    "BrandID": None,
                    "CorporateDetails": None,
                    "CustomerPicture": None,
                    "StaffDetails": None,
                }
            ],
            "ResponseStatus": True,
            "Errors": [],
        },
    ),
    Endpoint(HTTPMethod.PATCH, f"{BASE_URL}/api/Customer/Patch", HTTPStatus.OK, {}),
]
